homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('hobbie/', views.hobbie, name='hobbie'),
    path('reachme/', views.reachme, name='reachme'),
    path('jadwal/', views.join, name='Schedule'),
    path('<int:pk>', views.delete, name = 'delete'),
    # dilanjutkan ...
]

rajasihombing/urls.py
from django.urls import path
from . import views

app_name = 'rajasihombing'

urlpatterns = [
    path('', views.index, name='index'),
    # path('profile/', views.profile, name='profile'),
    # dilanjutkan ...
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('rajasihombing.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    matkul = models.CharField(blank=False, max_length= 100)
    dosen = models.CharField(blank=False, max_length= 100)
    sks = models.IntegerField(blank=False)
    deskripsi = models.CharField(blank=False, max_length= 150)
    semester = models.CharField(blank=False, max_length= 150)
    kelas = models.CharField(blank=False, max_length= 150, help_text ='Masukkan tahun semester, e.g 2020/2021')

rajasihombing/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms

class SchedForm(forms.Form):
    matkul = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Mata Kuliah',
        'type' : 'text',
        'required' : True,
    }))
    dosen = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Dosen',
        'type' : 'text',
        'required' : True,
    }))
    sks = forms.IntegerField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah sks',
        'type' : 'text',
        'required' : True,
    }))
    deskripsi = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Deskripsi Mata Kuliah',
        'type' : 'text',
        'required' : True,
    }))
    semester = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Semester',
        'type' : 'text',
        'required' : True,
    }))
    kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Kelas',
        'type' : 'text',
        'required' : True,
    }))

homepage/views.py
from django.shortcuts import render, redirect
from .models import Schedule as jadwal
from .forms import SchedForm

# Create your views here.
def aboutme(request):
    return render(request, 'aboutme.html')

def hobbie(request):
    return render(request, 'hobbie.html')

def home(request):
    return render(request, 'home.html')

def reachme(request):
    return render(request, 'reachme.html')

def join(request):
    if request.method == 'POST':
        form = SchedForm(request.POST)
        if form.is_valid():
            schd = jadwal()
            schd.matkul = form.cleaned_data['matkul']
            schd.dosen = form.cleaned_data['dosen']
            schd.sks = form.cleaned_data['sks']
            schd.deskripsi = form.cleaned_data['deskripsi']
            schd.semester = form.cleaned_data['semester']
            schd.kelas = form.cleaned_data['kelas']
            schd.save() 
        return redirect("/jadwal")

    else:
            schd = jadwal.objects.all()
            form = SchedForm()
            response = {'schd':schd, 'form': form}
            return render(request, 'jadwal.html', response)

def delete(request, pk):
    if request.method == 'POST':
        form = SchedForm(request.POST)
        if form.is_valid():
            schd = jadwal()
            schd.matkul = form.cleaned_data['matkul']
            schd.dosen = form.cleaned_data['dosen']
            schd.sks = form.cleaned_data['sks']
            schd.deskripsi = form.cleaned_data['deskripsi']
            schd.semester = form.cleaned_data['semester']
            schd.kelas = form.cleaned_data['kelas']
            schd.save() 
        return redirect("/jadwal")
    else:
            jadwal.objects.filter(pk = pk).delete()
            data = jadwal.objects.all()
            form = SchedForm()
            response = {
                "schd" : data,
                "form": form
            }
            return render(request, 'jadwal.html', response)

rajasihombing/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

homepage/templates/aboutme.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <!-- <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>About Me</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css"> -->

    </head>

    <body>

        
        <!-- Buat Navbar -->
        
        <!-- <nav class="navbar navbar-expand-sm navbar-light bg-light" style="background-color: #404962;">
            <a href="#" class="navbar-brands">Home</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
                <span class="navbar-toggler-icon"></span> 
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="{% url 'homepage:home' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:aboutme' %}" class="nav-link">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:hobbie' %}" class="nav-link">Hobbies</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:reachme' %}" class="nav-link">Reach Me</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'rajasihombing:index' %}" class="nav-link">Story 1</a>
                    </li>
                </ul>
            </div>
        </nav> -->

        <!-- Baris nama / Biodata-->

        {% include "navbar.html" %}
        
        <div class="container-fluid my-container">
            <div class="row">
                <div class="col-md-4 my-col col-foto">
                    <div class="container-fluid foto";>
                    </div>
                </div>
                <div class="col-md-8 my-col col-biodata">
                    <h1 id="nama">Raja Sihombing</h1>
                </div>
            </div>
            <div class="row">
                <div class="col my-col col-cerita-singkat">
                    <p class="cerita-singkat">“ Hai! nama saya Raja Sihombing. Saya mendeskripsikan diri saya sebagai seseorang yang berantusias dalam bidang sains dan teknologi. Saat ini saya sedang menempuh pendidikan S1 di Fasilkom Universitas Indonesia. Saya sendiri merupakan orang yang senang untuk berorganisasi. Adapun beberapa soft skill yang terus saya asah hingga saat ini adalah leadership dan public speaking. Menurut saya, terlepas dari seberapa pintar orang dalam akademis, dua hal tersebut sangatlah perlu untuk dikuasai. “
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5 order-md-12 my-col col-education">
                    <h1 id="edukasi">Education</h1>
                </div>
                <div class="col-md-7 order-md-1 my-col col-sekolah-dimana">
                    <div class="pendidikan">
                        <h2>Don Bosco II</h2>
                        <h2>SMAN 68 Jakarta</h2>
                        <h2>Fasilkom UI</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-7 my-col col-track">
                    <h1 id="track-record">
                        Track Record
                    </h1> 
                </div>
                <div class="col-md-5 my-col col-pengalaman">
                    <div class="pengalaman">
                        <h2>Ketua Osis SMAN 68 Jakarta</h2>
                        <h2>Perlap Wisgan</h2>
                        <h2>Sponsorship Compfest 12</h2>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

homepage/templates/hobbie.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Hobbie</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

    </head>

    <body>

        
        <!-- Buat Navbar -->
        
        <nav class="navbar navbar-expand-sm navbar-light bg-light" style="background-color: #404962;">
            <a href="#" class="navbar-brands">Home</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
                <span class="navbar-toggler-icon"></span> 
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="{% url 'homepage:home' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:aboutme' %}" class="nav-link">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:hobbie' %}" class="nav-link">Hobbies</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:reachme' %}" class="nav-link">Reach Me</a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Baris nama / Biodata-->
        
        <div class="container-fluid my-container-hobbie">
            <div class="row row-hobbie">
                <div class="col-md-4 col-hobbie-game col-hobbie">
                    <div class="isi-hobbie" id="game">
                        <br>
                        <h1>GAME</h1>
                        <br><br>
                        <p>
                            - Call of Duty <br>
                            - CSGO <br>
                            - Insurgency <br>
                            - StarCraft II <br>
                            - City Skyline <br>
                            <br>
                            you name it..
                        </p>
                    </div>
                </div>
                <div class="col-md-4 col-hobbie-music col-hobbie">
                    <div class="isi-hobbie" id="music">
                        <br>
                        <h1>MUSIC</h1>
                        <br><br>
                        <p>
                            - Billy Joel <br>
                            - David Bowie <br>
                            - Utha Likumahua <br>
                            - Atlantic Starr <br>
                            - Sheila Majid <br>
                            <br>
                            and so on...
                            <br>
                        </p>
                    </div>
                </div>
                <div class="col-md-4 col-hobbie-read col-hobbie">
                    <div class="isi-hobbie " id="read">
                        <br>
                        <h1>READ</h1>
                        <br><br>
                        <p>
                            - Mostly Arcticle <br>
                            - News <br>
                            - Memes <br>
                            <br>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

homepage/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Home</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

    </head>
    <body style="background-color: #FFDA58">

        
        <!-- Buat Navbar -->
        
        <!-- <nav class="navbar navbar-expand-sm navbar-light bg-light" style="background-color: #404962;">
            <a href="#" class="navbar-brands">Home</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
                <span class="navbar-toggler-icon"></span> 
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="{% url 'homepage:home' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:aboutme' %}" class="nav-link">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:hobbie' %}" class="nav-link">Hobbies</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:reachme' %}" class="nav-link">Reach Me</a>
                    </li>
                </ul>
            </div>
        </nav> -->

        <!-- Baris nama / Biodata-->
        
        <div class="container-fluid home-container">
            <div class="row home-row">
                <div class="col-md-4 home-col">
                    <a href="{% url 'homepage:aboutme' %}" class="nav-link">
                        <div class="home-1">
                            <p class="home-text">
                                A<br>B<br>O<br>U<br>T<br><br>M<br>E
                            </p>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 home-col">
                    <a href="{% url 'homepage:hobbie' %}" class="nav-link">
                        <div class="home-2">
                            <p class="home-text">
                                H<br>O<br>B<br>B<br>I<br>E<br>S
                            </p>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 home-col">
                    <a href="{% url 'homepage:reachme' %}" class="nav-link">
                        <div class="home-3">
                            <p class="home-text"> 
                                C<br>O<br>N<br>T<br>A<br>C<br>T
                            </p>
                        </div>
                    </a>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

homepage/templates/jadwal.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>REACH ME</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

    </head>

    <body>

        
        <!-- Buat Navbar -->
         
        <nav class="navbar navbar-expand-sm navbar-light bg-light" style="background-color: #404962;">
            <a href="#" class="navbar-brands">Home</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
                <span class="navbar-toggler-icon"></span> 
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="{% url 'homepage:home' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:aboutme' %}" class="nav-link">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:hobbie' %}" class="nav-link">Hobbies</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:reachme' %}" class="nav-link">Reach Me</a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Baris nama / Biodata-->
        
        <div class="container">
            <h1 style="text-align: center;">S C H E D U L E</h1>
                <div class="row">
                    <div class="col-sm-6">
                            <form action='' method="POST">
                                {% csrf_token %}
                                {{ form }}
                                <br>
                                <div class="centre-items">
                                    <input type="submit" class="btn btn-primary" value="Add Schedule" style="background-color: black; border-color: black;">
                                </div>
                            </form>
                    </div>
                      <div class="col-sm-6">
                        <table class="table">
                            <thead>
                            <tr>
                               <th scope="col">Mata Kuliah</th>
                               <th scope="col">Dosen</th>
                               <th scope="col">SKS</th>
                               <th scope="col">Deskripsi</th>
                               <th scope="col">Semester</th>
                               <th scope="col">Kelas</th>
                               <th scope="col">Delete</th>
                            </tr>
                        </thead>
                        <br>
                        <tbody>
                            {% for jadwal in schd %}
                            <tr>
                                <th scope="row">{{jadwal.matkul}}</th>
                                <td>{{jadwal.dosen}}</td>
                                <td>{{jadwal.sks}}</td>
                                <td>{{jadwal.deskripsi}}</td>
                                <td>{{jadwal.semester}}</td>
                                <td>{{jadwal.kelas}}</td>
                                <td><a href="{% url 'homepage:delete' pk=jadwal.pk %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash"></i></button></a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                          </div>
                      </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

homepage/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>About Me</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

    </head>

    <body>

        <!-- Buat Navbar -->
        
        <nav class="navbar navbar-expand-sm navbar-light bg-light" style="background-color: #404962;">
            <a href="#" class="navbar-brands">Home</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
                <span class="navbar-toggler-icon"></span> 
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="{% url 'homepage:home' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:aboutme' %}" class="nav-link">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:hobbie' %}" class="nav-link">Hobbies</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:reachme' %}" class="nav-link">Reach Me</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'rajasihombing:index' %}" class="nav-link">Story 1</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:Schedule' %}" class="nav-link">Schedule</a>
                    </li>
                </ul>
            </div>
        </nav>

    </body>
</html>

homepage/templates/reachme.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>REACH ME</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

    </head>

    <body>

        
        <!-- Buat Navbar -->
         
        <nav class="navbar navbar-expand-sm navbar-light bg-light" style="background-color: #404962;">
            <a href="#" class="navbar-brands">Home</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
                <span class="navbar-toggler-icon"></span> 
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="{% url 'homepage:home' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:aboutme' %}" class="nav-link">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:hobbie' %}" class="nav-link">Hobbies</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'homepage:reachme' %}" class="nav-link">Reach Me</a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Baris nama / Biodata-->
        
        <div class="container-fluid my-container-reach">
            <div class="row row-reach-me">
                <div id="reach-h1">
                    <h1>REACH ME</h1>
                </div>
            </div>
            <div class="row row-reach-me">
                <div class="col col-md-3 order-md-1 col-sosmed ig">
                    <h3>Instagram: <br> rajajames_</h3>
                </div>
                <div class="col col-md-3 order-md-2 col-sosmed line">
                    <h3>Line: <br> rajajamessihombing</h3>
                </div>
                <div class="col col-md-3 order-md-3 col-sosmed email">
                    <h3>Email: <br> rajasihombing2612@gmail.com</h3>
                </div>
                <div class="col col-md-3 order-md-4 col-sosmed spotify">
                    <h3>Spotify: <br> Raja Sihombing</h3>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

rajasihombing/templates/index.html
<!DOCTYPE html>
{% load static %}

<html>
    <table>
        <tr>
            <td>
                Hello World
            </td>
        </tr>
        <tr>
            <td>
                Nama
            </td>
            <td>
                Raja Sihombing
            </td>
        </tr>
        <tr>
            <td>
                NPM
            </td>
            <td>
                1906308066
            </td>
        </tr>
        <tr>
            <td>
                Angkatan
            </td>
            <td>
                2019
            </td>
        </tr>
        <tr>
            <td>
                Hobi
            </td>
            <td>
                Main game, Mendengarkan musik
            </td>
        </tr>
        <tr>
            <td>
                Deskripsi diri
            </td>
            <td>
                Saya merupakan orang yang sangat antusias terhadap teknologi
            </td>
        </tr>
        <tr>
            <td>
                Tempat Kuliah
            </td>
            <td>
                Fasilkom Universitas Indonesia
            </td>
        </tr>
        <tr>
            <td>
                Riwat Pendidikan
            </td>
            <td>
                SMP: Don Bosco II, SMA: SMAN 68 Jakarta
            </td>
        </tr>
        <tr>
            <td>
                Media Sosial
            </td>
            <td>
                Line: rajajamessihombing
            </td>
        </tr>
    </table>
</html>